### PR TITLE
use latest sls version

### PR DESCRIPTION
**Pull request by sfaisalj**

### CODE REVIEW

**Comment by sfaisalj** [comment]
[Determine if AWS States Changes Require Serverless Upgrades](https://trello.com/c/bHjGfOAL/350-determine-if-aws-states-changes-require-serverless-upgrades)

**Review by brbatwork — CHANGES_REQUESTED** [review]
Would you be willing to attach why this change is necessary to the ticket?

**Review by brbatwork — APPROVED** [review]
Tested in local stack across gateway_comp, batch_comp, customer_comp, context_user, context_assessment, context_notification, analytics_etl, context_message, and platmon.

**Comment by sfaisalj** [comment]
> Would you be willing to attach why this change is necessary to the ticket?

Yeap! Our third party tool "Serverless Framework" has actually implemented these new Lambda provisioning states, and we are taking this opportunity to keep our tooling updated.

All AWS CLIs and SDKs have supported monitoring Lambda function states transitions since the original announcement in 2019. Infrastructure as code tools such as AWS CloudFormation, AWS SAM, Serverless Framework, Hashicorp Terraform (>=2.40.0), and Cloud Custodian (>=0.9.14.0) also already support states. 

https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/

**Pull request merged**
