### PR TITLE
Update to correct URL

### PR DESCRIPTION
**Pull request by brbatwork**

### CODE REVIEW

**Review by sfaisalj — APPROVED** [review]
Looks good

**Review by sampontec — COMMENTED** [review]
Should the other images be updated?

**Comment by brbatwork** [comment]
> Should the other images be updated?

When it comes time to publish a new version of the other ones, then it can be updated.

**Comment by sfaisalj** [comment]
[Determine if AWS States Changes Require Serverless Upgrades](https://trello.com/c/bHjGfOAL/350-determine-if-aws-states-changes-require-serverless-upgrades)

**Pull request merged**
