### PR TITLE
Add awscli to build image used by workforce

### PR DESCRIPTION
**Pull request by brbatwork**

### CODE REVIEW

**Comment by brbatwork** [comment]
[Add the APK files to anvl.com](https://trello.com/c/mQGCv8yA/415-add-the-apk-files-to-anvlcom)

**Review by sampontec — APPROVED** [review]

**Review by sampontec — CHANGES_REQUESTED** [review]
Shouldn't the api be bumped up?

**Comment by brbatwork** [comment]
> Shouldn't the api be bumped up?

@sampontec Oh, I didn't even see that.  It is not needed for the current card, but I can try it now anyway.

**Comment by brbatwork** [comment]
> > Shouldn't the api be bumped up?
> 
> @sampontec Oh, I didn't even see that. It is not needed for the current card, but I can try it now anyway.

@sampontec There is no 31 image from circle `docker.io/circleci/android:api-31: not found`.  Recommend changing this value as part of a more deliberate effort of upgrading our tooling, and not tacking it onto this effort.

**Review by sampontec — APPROVED** [review]

**Comment by brbatwork** [comment]
> Sounds good. Has a card been made for it?

https://trello.com/c/Z4QcxMqs

**Pull request merged**
