### PR TITLE
using latest from circle

### PR DESCRIPTION
**Pull request by sfaisalj**

### CODE REVIEW

**Comment by sfaisalj** [comment]
[Migrate to new CircleCI images](https://trello.com/c/fzWeQEr5/334-migrate-to-new-circleci-images)

**Review by sampontec — COMMENTED** [review]
have these been published?

**Comment by sfaisalj** [comment]
> have these been published?

Not yet. Wanted to wait for review

**Comment by sfaisalj** [comment]
@brbatwork and @sampontec Review needed for this one as well

**Review by brbatwork — APPROVED** [review]

**Pull request merged**
